Practice3
pj100-team/react-v3 pull request #20
Opened 2023-10-17 06:25 UTC by saeUemoto

動作↓
https://github.com/pj100-team/react-v3/assets/146803619/bf7d7379-57fe-462e-b50d-8ac3f7beb99a

早く終わったので、２と３の解答をまとめてプッシュします。
（ローカルには２だけのブランチもあります。）

2023-10-17 08:04 UTC, AubreyLin0 commented on src/App.tsx
> +          onChange={() =>
今の書き方でもいいですが、チェックボックスの値で文字が見えるかどうかで判断した方が確実だと思います。
チェックボックスの値はonChangeのeventの中にあります。
console.logしてみて、eventの中身は何か入っているのが一度確認してみてください。
`onChange={(event)=>{console.log(event.target)}}`

https://developer.mozilla.org/ja/docs/Web/API/HTMLElement/change_event

そして、条件分岐でsetTextVisibilityを二回書くより、setTextVisibility内で条件分岐を書いた方がいいです。

2023-10-17 08:04 UTC, AubreyLin0 commented on src/App.tsx
> +        {
`{}`はなくてもいいですね

2023-10-17 08:05 UTC, AubreyLin0 commented
conflictの解消をお願いしますー！

2023-10-18 07:36 UTC, AubreyLin0 commented on src/App.tsx
> +  const [isTextVisible, setTextVisibility] = useState<boolean>(false);
暗黙なルールだと思いますが、useStateを使う時に前後一致の名前にしてほしいです。
例えば：`[isTextVisible, setIsTextVisibility]`

2023-10-18 07:36 UTC, AubreyLin0 commented on src/App.tsx
> +            setTextVisibility(event.target.checked ? true : false);
`event.target.checked`の型自体がboolean型なので、`setTextVisibility(event.target.checked)`でいいと思います。

2023-10-23 04:30 UTC, RspSang requested changes

2023-10-23 04:30 UTC, RspSang commented on src/App.tsx
> +        </label>
styleで調整した理由はありますでしょうか。
checkboxにチェックが入ってない場合レンダリングしない方が効率的だと思います！

2023-10-23 04:30 UTC, RspSang commented on src/components/Button.tsx
> +      className={`${color} ${backGroundColor} py-2 px-4 rounded mx-5`}
color backgroundColorは想定される値をinterfaceで定義して必要に応じて使った方がミスが起こりにくいと思います。
また、interfaceでborderColorが指定されていますが使用されていないみたいです

2023-10-23 04:30 UTC, RspSang commented on src/components/Input.tsx
> +  }
inputで既にtypeを指定しているので一つのinputでコントロールできそうです！

2023-10-23 04:30 UTC, RspSang commented on src/components/Input.tsx
> +  styles: string;
Buttonコンポーネントのstyles propsとpropsの単位が違う理由などありますでしょうか？
Buttonではcolor,backGroundColorで渡していますが、ここはstylesとして渡していることが気になります

2023-10-23 07:36 UTC, RspSang requested changes

2023-10-23 07:36 UTC, RspSang commented on src/components/CheckBox.tsx
> +  value?: string;
valueは使われてないので削除してもいいと思います！

2023-10-23 07:36 UTC, RspSang commented on src/components/Input.tsx
> +  value?: string;
valueは今のところ必須だと思うので`?`は必要ないと思います！

2023-10-23 07:36 UTC, RspSang commented on src/App.tsx
> +          styles=" h-8 border-2"
空白が入っています

2023-10-23 08:17 UTC, RspSang approved these changes

2023-10-23 08:17 UTC, merged