Practice5 takahashi tomoya
pj100-team/react-v3 pull request #32
Opened 2024-01-17 01:34 UTC by tomoya0527

practice 5の構築が完了しましたので、PRお願いいたします。

https://github.com/pj100-team/react-v3/assets/122339519/f65e3c09-6476-4f83-a4fe-1e7a23dfa579

2024-01-17 04:44 UTC, HirokiKotera13456 commented on src/App.tsx
> +        {/* <section className="flex flex-col gap-40"> */}
PR時には、不要な文は削除してください。

2024-01-17 04:44 UTC, HirokiKotera13456 commented on src/components/allDeleteTodo.tsx
> +  hasSelectedState: any;
anyは極力使わないでください。
どの型が正しいか考えてみてください。

2024-01-17 04:44 UTC, HirokiKotera13456 commented on src/templates/practice5.tsx
> +// import TodoItem from '../components/todoItem';
不要なimport文の削除お願いします

2024-01-17 04:44 UTC, HirokiKotera13456 commented
実装ありがとうございます！！
コメント残しました！

2024-01-17 04:52 UTC, RspSang requested changes

2024-01-17 04:52 UTC, RspSang commented on src/App.tsx
> +        {/* <section className="flex flex-col gap-40"> */}
必要ないコメントアウトは削除をお願いします！

2024-01-17 04:52 UTC, RspSang commented on src/templates/practice5.tsx
> +// import TodoItem from '../components/todoItem';
コメントアウトの削除をお願いします！

2024-01-17 04:52 UTC, RspSang commented on src/templates/practice5.tsx
> +        <TodoList items={todos} setTodos={setTodos} setHasSelected={setHasSelected} hasSelected={hasSelected} />
TodoListのitemsのprops名は`items`より`todos`にした方がいいと思います。
TodoListのコンポーネントで`todos`と`items`のstateが両方存在しているのか誤解する可能性があると思いました。

2024-01-17 04:52 UTC, RspSang commented on src/templates/practice5.tsx
> +      });
filterを使っているので `todos.filter((todo) => !todo.selected)`だけでいいと思います。
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoItem.tsx
> +    <tr key={id}>
ここでマップしていないので、keyはいらないと思います

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoItem.tsx
> +          className="cursor-pointer"
`cursor-pointer`なくてもいいと思います

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoItem.tsx
> +        <input
ボタンだったらinputじゃなくて、buttonの方がいいと思います

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoList.tsx
> +    if (isSelected) {
`isSelected`だと選択されているという命名になるので、`isAllSelected`の方が適切だと思います

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoList.tsx
> +      setTodos((todos) => {
これでいいと思います
```typescript
setTodos((todos) => {
        return todos.map((todo) => {
          return { ...todo, selected: isAllSelected };
        });
      });
```

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoList.tsx
> +    setHasSelected((prev) => !prev);
`setHasSelected`はどのチェックボックスのことでしょうか？
全て選択の方？個別選択の方？

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoList.tsx
> +      const newTodos = todos.filter((todo) => {
これでいいと思います
```typescipt
const newTodos = todos.filter((todo) => {
  return todo.id !== targetID;
});
```

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoList.tsx
> +              onChange={() => handleAllSelect(!hasSelected)}
`hasSelected`を使うよりonChangeのeventの中にevent.target.checkedの方から値を取った方がいいと思います
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event

2024-01-17 07:38 UTC, AubreyLin0 commented on src/components/todoList.tsx
> +              id={item.id}
`item`の中身を分けて渡すより`item`自体を渡したらどうですか

2024-01-17 07:38 UTC, AubreyLin0 commented on src/templates/practice5.tsx
> +  readonly id: number;
`id`は日付だと思うので、number型でいいですか？🤔

2024-01-17 07:38 UTC, AubreyLin0 commented on src/templates/practice5.tsx
> +  useEffect(() => {
`dependency`を書いてないと無限loopになりますので、`dependency`を追加してください
https://react.dev/reference/react/useEffect

2024-01-17 07:38 UTC, AubreyLin0 commented on src/templates/practice5.tsx
> +    setHasSelected(isDeleteBtnDisplay);
すみません、ここはあまり理解できなかったです。
削除ボタンが表示されるとチェックボックスがチェックされますか？🤔

2024-01-18 01:51 UTC, tomoya0527 commented on src/App.tsx
> +        {/* <section className="flex flex-col gap-40"> */}
すみません、消し忘れてました！
削除しました

2024-01-18 01:51 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +// import TodoItem from '../components/todoItem';
こちらも削除しました！

2024-01-18 01:52 UTC, tomoya0527 commented on src/App.tsx
> +        {/* <section className="flex flex-col gap-40"> */}
すみません、こちら消し忘れてました！
削除しました！

2024-01-18 01:52 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +// import TodoItem from '../components/todoItem';
こちらも同様に削除しました！

2024-01-18 02:06 UTC, tomoya0527 commented on src/components/allDeleteTodo.tsx
> +  hasSelectedState: any;
ご指摘ありがとうございます！
こちらboolean型に変更しました。

2024-01-18 02:09 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +        <TodoList items={todos} setTodos={setTodos} setHasSelected={setHasSelected} hasSelected={hasSelected} />
ご指摘ありがとうございます！
propsの命名は揃えた方が良いということで理解しました！
修正完了しております！

2024-01-18 02:12 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +      });
こちらもありがとうございます！
省略できるやつは省略していくようにしていきます！
修正しました！

2024-01-18 04:27 UTC, tomoya0527 commented on src/components/todoList.tsx
> +    setHasSelected((prev) => !prev);
こちらは一つでもチェックがあれば「一括削除」ボタンを表示するフラグを管理するstateで用意しています。
なのでどちらにも対応していますが、どちらかというと個別選択の方に依存する形で構築しています。

2024-01-18 04:29 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +  readonly id: number;
こちらはidに日付にgetTimeメソッドで変換したシリアル値を設定するようにしているためnumber型で定義しました

2024-01-18 04:31 UTC, tomoya0527 commented on src/components/addTodo.tsx
> +        className="p-form__input"
ご指摘ありがとうございます。
ボタンやテーブルのスタイルをタグごとに設定するのが煩わしかったため、tailwindのCSSを一つにまとめる機能で処理してしまいました。
どれか一つのフレームワークに揃えて書く必要ありとのことで理解しました。
修正済みです。

2024-01-18 04:33 UTC, tomoya0527 commented on src/components/allDeleteTodo.tsx
> +          : 'opacity-0 invisibl cursor-pointer'
こちら修正しました

2024-01-18 04:34 UTC, tomoya0527 commented on src/components/todoItem.tsx
> +    <tr key={id}>
ループ処理は必ずkeyがいるのだと思ってました。。。
アイテムをコンポーネントにしてる場合は必要ないんですね。
ご指摘ありがとうございます！

2024-01-18 04:37 UTC, tomoya0527 commented on src/components/todoItem.tsx
> +    <tr key={id}>
子コンポーネント側でkeyは設定する必要ないんですね。。
ご指摘ありがとうございます！
修正しました

2024-01-18 04:37 UTC, tomoya0527 commented on src/components/todoItem.tsx
> +          className="cursor-pointer"
修正しました

2024-01-18 04:37 UTC, tomoya0527 commented on src/components/todoItem.tsx
> +        <input
buttonタグへ変更しました

2024-01-18 04:38 UTC, tomoya0527 commented on src/components/todoList.tsx
> +    if (isSelected) {
ご指摘ありがとうございます！
変更しました！

2024-01-18 04:39 UTC, tomoya0527 commented on src/components/todoList.tsx
> +      setTodos((todos) => {
本当ですね、if文使わなくてよかったですね。。。
修正しました！

2024-01-18 04:39 UTC, tomoya0527 commented on src/components/todoList.tsx
> +      const newTodos = todos.filter((todo) => {
こちら修正しました

2024-01-18 04:40 UTC, tomoya0527 commented on src/components/todoList.tsx
> +              onChange={() => handleAllSelect(!hasSelected)}
stateを使うことに気を取られすぎてたみたいです、、、
ご指摘ありがとうございます！
修正しました！

2024-01-18 04:41 UTC, tomoya0527 commented on src/components/todoList.tsx
> +              id={item.id}
その発想浮かびませんでした！
ありがとうございます！
修正しました！

2024-01-18 04:42 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +  useEffect(() => {
本当ですね、すみません抜けてました。。。
todosステートを指定しました

2024-01-18 04:45 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +    setHasSelected(isDeleteBtnDisplay);
[こちら](https://github.com/pj100-team/react-v3/pull/32#discussion_r1454769043)同様一つでもチェックが入っていれば削除ボタンを表示する仕様にするために、useEffectとsetHasSelected(選択状態を管理するステート)を使っている次第です

2024-01-18 04:45 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +    const isDeleteBtnDisplay = todos.some((todo) => todo.selected === true);
ご確認ありがとうございます！
修正しました！

2024-01-18 04:53 UTC, RspSang approved these changes

2024-01-18 05:04 UTC, saeUemoto approved these changes

2024-01-18 23:49 UTC, AubreyLin0 commented on src/templates/practice5.tsx
> +    setHasSelected(isDeleteBtnDisplay);
仮に`isDeleteBtnDisplay`がtrueの場合、`hasSelected`もtrueになります。
そして、全てを選択のチェックボックスを押して、`handleAllSelect`が実行されて、`setHasSelected((prev) => !prev);`で`hasSelected`の値はfalseになります。削除ボタンが消えます。
もしこれで合っているなら、ここのロジックを修正した方がいいです。

2024-01-19 03:36 UTC, tomoya0527 commented on src/templates/practice5.tsx
> +    setHasSelected(isDeleteBtnDisplay);
ご指摘ありがとうございます！

`isDeleteBtnDisplay`と`hasSelected`の値が同じである必要があるから、全選択時の`setHasSelected((prev) => !prev);`は逆転させてしまってて予期しない挙動になるということですね。
うまくいってたのは`practice5.tsx`のuseEffect内にある`setHasSelected`がチェックボックスに一つでもチェックがあればTrueを入れるというロジックが入ってたから結果オーライになっていた、ということですかね🤔

今回は`handleAllSelect`内の`setHasSelected((prev) => !prev);`を削除するだけの修正をしました。
お手数ですがご確認よろしくお願いいたします🙇‍♂️

2024-01-19 04:27 UTC, AubreyLin0 commented on src/templates/practice5.tsx
> +    setHasSelected(isDeleteBtnDisplay);
@tomoya0527 
> isDeleteBtnDisplayとhasSelectedの値が同じである必要があるから、全選択時のsetHasSelected((prev) => !prev);は逆転させてしまってて予期しない挙動になるということですね。

そうですね。

修正ありがとうございます！

2024-01-19 04:27 UTC, AubreyLin0 approved these changes

2024-01-19 04:28 UTC, merged